<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Hardbound Submission Acknowledgement — #{{ $application->id }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 11px; color: #000; line-height: 1.5; }
        .logo { text-align: center; margin-bottom: 18px; }
        .logo img { height: 58px; }
        h1 { font-size: 12px; text-transform: uppercase; text-align: center;
             border: 1px solid #000; padding: 6px; margin: 0 0 22px; }
        table.details { border-collapse: collapse; margin: 12px 0 18px; width: 100%; }
        table.details td { padding: 3px 4px; vertical-align: top; }
        table.details td.label { width: 165px; }
        table.details td.sep { width: 8px; }
        .sig-line { margin-top: 44px; border-top: 1px solid #000; width: 280px; }
        .footer { margin-top: 34px; font-size: 8.5px; color: #555; border-top: 1px solid #ccc; padding-top: 6px; }
    </style>
</head>
<body>
    <div class="logo">
        <img src="{{ public_path('images/UTP_logo.png') }}" alt="Universiti Teknologi PETRONAS">
    </div>

    <h1>Hardbound Thesis Submission — Acknowledgement Receipt</h1>

    <p>
        The Centre for Graduate Studies acknowledges receipt and acceptance of the
        hardbound thesis detailed below. This receipt is issued on the approval of the
        Centre for Graduate Studies.
    </p>

    <table class="details">
        <tr><td class="label">Receipt No</td><td class="sep">:</td><td>UTP/CGS/HB/{{ $application->id }}</td></tr>
        <tr><td class="label">Candidate's Name</td><td class="sep">:</td><td>{{ $student?->name ?? '—' }}</td></tr>
        <tr><td class="label">Matric Number</td><td class="sep">:</td><td>{{ $detail->matric_no ?: '—' }}</td></tr>
        <tr><td class="label">Programme</td><td class="sep">:</td><td>{{ $detail->programme }}</td></tr>
        <tr><td class="label">Supervisor</td><td class="sep">:</td><td>{{ $detail->supervisor_name }}</td></tr>
        <tr><td class="label">Title of the Thesis</td><td class="sep">:</td><td><b>{{ $detail->thesis_title }}</b></td></tr>
        <tr><td class="label">Date Submitted</td><td class="sep">:</td><td>{{ $application->submitted_at?->format('j F Y') ?? '—' }}</td></tr>
        <tr><td class="label">Date Accepted</td><td class="sep">:</td><td>{{ $issuedAt->format('j F Y') }}</td></tr>
    </table>

    <p><b>Decisions recorded against this submission</b></p>
    <table class="details">
        @foreach ($application->history as $row)
            <tr>
                <td class="label">{{ $row->stage_label }}</td>
                <td class="sep">:</td>
                <td>
                    {{ ucfirst($row->decision) }}
                    on {{ $row->created_at?->format('j F Y') }}
                    @if ($row->remarks) — {{ $row->remarks }} @endif
                </td>
            </tr>
        @endforeach
    </table>

    <div class="sig-line"></div>
    <p>
        Non-Executive Officer<br>
        Centre for Graduate Studies<br>
        Universiti Teknologi PETRONAS
    </p>

    <div class="footer">
        Generated by UResearch 2.0 on {{ $issuedAt->format('j F Y, g:ia') }} and archived
        against Application #{{ $application->id }}. This receipt is issued electronically
        and is valid without a signature.
    </div>
</body>
</html>
