<?php

namespace App\Modules\Core\Support;

use Illuminate\Support\Str;

/**
 * The per-request Content-Security-Policy nonce.
 *
 * One random value per response, generated by the ContentSecurityPolicy
 * middleware and quoted both in the header and on every inline <script> the
 * page renders. A script tag carrying the right nonce runs; an injected one
 * cannot guess it, so it does not.
 *
 * Held here rather than on the request so a Blade view can reach it without
 * being handed it, which would mean threading a variable through every
 * controller and partial in the portal.
 */
final class Csp
{
    protected static ?string $nonce = null;

    /** Generates on first call, then stays fixed for the rest of the request. */
    public static function nonce(): string
    {
        return self::$nonce ??= Str::random(24);
    }

    /** Called by the middleware between requests in a long-lived worker. */
    public static function reset(): void
    {
        self::$nonce = null;
    }
}
